/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ComponentsComponentResponse : The base class for any component-returning object that may need to indicate information about the state of the component being returned.

#[derive(Debug, Serialize, Deserialize)]
pub struct ComponentsComponentResponse {
  #[serde(rename = "privacy")]
  privacy: Option<::models::ComponentsComponentPrivacySetting>
}

impl ComponentsComponentResponse {
  /// The base class for any component-returning object that may need to indicate information about the state of the component being returned.
  pub fn new() -> ComponentsComponentResponse {
    ComponentsComponentResponse {
      privacy: None
    }
  }

  pub fn set_privacy(&mut self, privacy: ::models::ComponentsComponentPrivacySetting) {
    self.privacy = Some(privacy);
  }

  pub fn with_privacy(mut self, privacy: ::models::ComponentsComponentPrivacySetting) -> ComponentsComponentResponse {
    self.privacy = Some(privacy);
    self
  }

  pub fn privacy(&self) -> Option<&::models::ComponentsComponentPrivacySetting> {
    self.privacy.as_ref()
  }

  pub fn reset_privacy(&mut self) {
    self.privacy = None;
  }

}



