/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsDestinyItemPreviewBlockDefinition : Items like Sacks or Boxes can have items that it shows in-game when you view details that represent the items you can obtain if you use or acquire the item.  This defines those categories, and gives some insights into that data's source.

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyItemPreviewBlockDefinition {
  /// If the preview data is derived from a fake \"Preview\" Vendor, this will be the hash identifier for the DestinyVendorDefinition of that fake vendor.
  #[serde(rename = "previewVendorHash")]
  preview_vendor_hash: Option<i32>,
  /// If the preview has an associated action (like \"Open\"), this will be the localized string for that action.
  #[serde(rename = "previewActionString")]
  preview_action_string: Option<String>,
  /// This is a list of the items being previewed, categorized in the same way as they are in the preview UI.
  #[serde(rename = "derivedItemCategories")]
  derived_item_categories: Option<Vec<::models::DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition>>
}

impl DestinyDefinitionsDestinyItemPreviewBlockDefinition {
  /// Items like Sacks or Boxes can have items that it shows in-game when you view details that represent the items you can obtain if you use or acquire the item.  This defines those categories, and gives some insights into that data's source.
  pub fn new() -> DestinyDefinitionsDestinyItemPreviewBlockDefinition {
    DestinyDefinitionsDestinyItemPreviewBlockDefinition {
      preview_vendor_hash: None,
      preview_action_string: None,
      derived_item_categories: None
    }
  }

  pub fn set_preview_vendor_hash(&mut self, preview_vendor_hash: i32) {
    self.preview_vendor_hash = Some(preview_vendor_hash);
  }

  pub fn with_preview_vendor_hash(mut self, preview_vendor_hash: i32) -> DestinyDefinitionsDestinyItemPreviewBlockDefinition {
    self.preview_vendor_hash = Some(preview_vendor_hash);
    self
  }

  pub fn preview_vendor_hash(&self) -> Option<&i32> {
    self.preview_vendor_hash.as_ref()
  }

  pub fn reset_preview_vendor_hash(&mut self) {
    self.preview_vendor_hash = None;
  }

  pub fn set_preview_action_string(&mut self, preview_action_string: String) {
    self.preview_action_string = Some(preview_action_string);
  }

  pub fn with_preview_action_string(mut self, preview_action_string: String) -> DestinyDefinitionsDestinyItemPreviewBlockDefinition {
    self.preview_action_string = Some(preview_action_string);
    self
  }

  pub fn preview_action_string(&self) -> Option<&String> {
    self.preview_action_string.as_ref()
  }

  pub fn reset_preview_action_string(&mut self) {
    self.preview_action_string = None;
  }

  pub fn set_derived_item_categories(&mut self, derived_item_categories: Vec<::models::DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition>) {
    self.derived_item_categories = Some(derived_item_categories);
  }

  pub fn with_derived_item_categories(mut self, derived_item_categories: Vec<::models::DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition>) -> DestinyDefinitionsDestinyItemPreviewBlockDefinition {
    self.derived_item_categories = Some(derived_item_categories);
    self
  }

  pub fn derived_item_categories(&self) -> Option<&Vec<::models::DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition>> {
    self.derived_item_categories.as_ref()
  }

  pub fn reset_derived_item_categories(&mut self) {
    self.derived_item_categories = None;
  }

}



