/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDestinyVendorInteractionRewardSelection : When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be.

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDestinyVendorInteractionRewardSelection {
}

impl DestinyDestinyVendorInteractionRewardSelection {
  /// When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be.
  pub fn new() -> DestinyDestinyVendorInteractionRewardSelection {
    DestinyDestinyVendorInteractionRewardSelection {
    }
  }

}

// TODO enum 
// List of Destiny.DestinyVendorInteractionRewardSelection
//const (
//  
//  
//  
//)


