/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition : Data related to what happens while a plug is being inserted, mostly for UI purposes.

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition {
  /// How long it takes for the Plugging of the item to be completed once it is initiated, if you care.
  #[serde(rename = "actionExecuteSeconds")]
  action_execute_seconds: Option<i32>
}

impl DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition {
  /// Data related to what happens while a plug is being inserted, mostly for UI purposes.
  pub fn new() -> DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition {
    DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition {
      action_execute_seconds: None
    }
  }

  pub fn set_action_execute_seconds(&mut self, action_execute_seconds: i32) {
    self.action_execute_seconds = Some(action_execute_seconds);
  }

  pub fn with_action_execute_seconds(mut self, action_execute_seconds: i32) -> DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition {
    self.action_execute_seconds = Some(action_execute_seconds);
    self
  }

  pub fn action_execute_seconds(&self) -> Option<&i32> {
    self.action_execute_seconds.as_ref()
  }

  pub fn reset_action_execute_seconds(&mut self) {
    self.action_execute_seconds = None;
  }

}



