/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyHistoricalStatsDestinyHistoricalStatsValue {
  /// Unique ID for this stat
  #[serde(rename = "statId")]
  stat_id: Option<String>,
  /// Basic stat value.
  #[serde(rename = "basic")]
  basic: Option<Object>,
  /// Per game average for the statistic, if applicable
  #[serde(rename = "pga")]
  pga: Option<Object>,
  /// Weighted value of the stat if a weight greater than 1 has been assigned.
  #[serde(rename = "weighted")]
  weighted: Option<Object>
}

impl DestinyHistoricalStatsDestinyHistoricalStatsValue {
  pub fn new() -> DestinyHistoricalStatsDestinyHistoricalStatsValue {
    DestinyHistoricalStatsDestinyHistoricalStatsValue {
      stat_id: None,
      basic: None,
      pga: None,
      weighted: None
    }
  }

  pub fn set_stat_id(&mut self, stat_id: String) {
    self.stat_id = Some(stat_id);
  }

  pub fn with_stat_id(mut self, stat_id: String) -> DestinyHistoricalStatsDestinyHistoricalStatsValue {
    self.stat_id = Some(stat_id);
    self
  }

  pub fn stat_id(&self) -> Option<&String> {
    self.stat_id.as_ref()
  }

  pub fn reset_stat_id(&mut self) {
    self.stat_id = None;
  }

  pub fn set_basic(&mut self, basic: Object) {
    self.basic = Some(basic);
  }

  pub fn with_basic(mut self, basic: Object) -> DestinyHistoricalStatsDestinyHistoricalStatsValue {
    self.basic = Some(basic);
    self
  }

  pub fn basic(&self) -> Option<&Object> {
    self.basic.as_ref()
  }

  pub fn reset_basic(&mut self) {
    self.basic = None;
  }

  pub fn set_pga(&mut self, pga: Object) {
    self.pga = Some(pga);
  }

  pub fn with_pga(mut self, pga: Object) -> DestinyHistoricalStatsDestinyHistoricalStatsValue {
    self.pga = Some(pga);
    self
  }

  pub fn pga(&self) -> Option<&Object> {
    self.pga.as_ref()
  }

  pub fn reset_pga(&mut self) {
    self.pga = None;
  }

  pub fn set_weighted(&mut self, weighted: Object) {
    self.weighted = Some(weighted);
  }

  pub fn with_weighted(mut self, weighted: Object) -> DestinyHistoricalStatsDestinyHistoricalStatsValue {
    self.weighted = Some(weighted);
    self
  }

  pub fn weighted(&self) -> Option<&Object> {
    self.weighted.as_ref()
  }

  pub fn reset_weighted(&mut self) {
    self.weighted = None;
  }

}



