/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyHistoricalStatsDefinitionsDestinyStatsMergeMethod {
}

impl DestinyHistoricalStatsDefinitionsDestinyStatsMergeMethod {
  pub fn new() -> DestinyHistoricalStatsDefinitionsDestinyStatsMergeMethod {
    DestinyHistoricalStatsDefinitionsDestinyStatsMergeMethod {
    }
  }

}

// TODO enum 
// List of Destiny.HistoricalStats.Definitions.DestinyStatsMergeMethod
//const (
//  
//  
//  
//)


