/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsDestinyBubbleDefinition : Basic identifying data about the bubble. Combine with DestinyDestinationBubbleSettingDefinition - see DestinyDestinationDefinition.bubbleSettings for more information.

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyBubbleDefinition {
  /// The identifier for the bubble: only guaranteed to be unique within the Destination.
  #[serde(rename = "hash")]
  hash: Option<i32>
}

impl DestinyDefinitionsDestinyBubbleDefinition {
  /// Basic identifying data about the bubble. Combine with DestinyDestinationBubbleSettingDefinition - see DestinyDestinationDefinition.bubbleSettings for more information.
  pub fn new() -> DestinyDefinitionsDestinyBubbleDefinition {
    DestinyDefinitionsDestinyBubbleDefinition {
      hash: None
    }
  }

  pub fn set_hash(&mut self, hash: i32) {
    self.hash = Some(hash);
  }

  pub fn with_hash(mut self, hash: i32) -> DestinyDefinitionsDestinyBubbleDefinition {
    self.hash = Some(hash);
    self
  }

  pub fn hash(&self) -> Option<&i32> {
    self.hash.as_ref()
  }

  pub fn reset_hash(&mut self) {
    self.hash = None;
  }

}



