/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyEntitiesItemsDestinyItemSocketState : The status of a given item's socket. (which plug is inserted, if any: whether it is enabled, what \"reusable\" plugs can be inserted, etc...)

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyEntitiesItemsDestinyItemSocketState {
  /// The currently active plug, if any.  Note that, because all plugs are statically defined, its effect on stats and perks can be statically determined using the plug item's definition. The stats and perks can be taken at face value on the plug item as the stats and perks it will provide to the user/item.
  #[serde(rename = "plugHash")]
  plug_hash: Option<i32>,
  /// Even if a plug is inserted, it doesn't mean it's enabled.  This flag indicates whether the plug is active and providing its benefits.
  #[serde(rename = "isEnabled")]
  is_enabled: Option<bool>,
  /// If a plug is inserted but not enabled, this will be populated with indexes into the plug item definition's plug.enabledRules property, so that you can show the reasons why it is not enabled.
  #[serde(rename = "enableFailIndexes")]
  enable_fail_indexes: Option<Vec<i32>>,
  /// If the item supports reusable plugs, this is the list of plug item hashes that are currently allowed to be used for this socket. (sometimes restrictions may cause reusable plugs defined on the item definition to not be valid, so you should trust the instanced reusablePlugHashes list rather than the definition's list)  A Reusable Plug is a plug that you can *always* insert into this socket, regardless of whether or not you have the plug in your inventory. In practice, a socket will *either* have reusable plugs *or* it will allow for plugs in your inventory to be inserted. See DestinyInventoryItemDefinition.socket for more info.
  #[serde(rename = "reusablePlugHashes")]
  reusable_plug_hashes: Option<Vec<i32>>
}

impl DestinyEntitiesItemsDestinyItemSocketState {
  /// The status of a given item's socket. (which plug is inserted, if any: whether it is enabled, what \"reusable\" plugs can be inserted, etc...)
  pub fn new() -> DestinyEntitiesItemsDestinyItemSocketState {
    DestinyEntitiesItemsDestinyItemSocketState {
      plug_hash: None,
      is_enabled: None,
      enable_fail_indexes: None,
      reusable_plug_hashes: None
    }
  }

  pub fn set_plug_hash(&mut self, plug_hash: i32) {
    self.plug_hash = Some(plug_hash);
  }

  pub fn with_plug_hash(mut self, plug_hash: i32) -> DestinyEntitiesItemsDestinyItemSocketState {
    self.plug_hash = Some(plug_hash);
    self
  }

  pub fn plug_hash(&self) -> Option<&i32> {
    self.plug_hash.as_ref()
  }

  pub fn reset_plug_hash(&mut self) {
    self.plug_hash = None;
  }

  pub fn set_is_enabled(&mut self, is_enabled: bool) {
    self.is_enabled = Some(is_enabled);
  }

  pub fn with_is_enabled(mut self, is_enabled: bool) -> DestinyEntitiesItemsDestinyItemSocketState {
    self.is_enabled = Some(is_enabled);
    self
  }

  pub fn is_enabled(&self) -> Option<&bool> {
    self.is_enabled.as_ref()
  }

  pub fn reset_is_enabled(&mut self) {
    self.is_enabled = None;
  }

  pub fn set_enable_fail_indexes(&mut self, enable_fail_indexes: Vec<i32>) {
    self.enable_fail_indexes = Some(enable_fail_indexes);
  }

  pub fn with_enable_fail_indexes(mut self, enable_fail_indexes: Vec<i32>) -> DestinyEntitiesItemsDestinyItemSocketState {
    self.enable_fail_indexes = Some(enable_fail_indexes);
    self
  }

  pub fn enable_fail_indexes(&self) -> Option<&Vec<i32>> {
    self.enable_fail_indexes.as_ref()
  }

  pub fn reset_enable_fail_indexes(&mut self) {
    self.enable_fail_indexes = None;
  }

  pub fn set_reusable_plug_hashes(&mut self, reusable_plug_hashes: Vec<i32>) {
    self.reusable_plug_hashes = Some(reusable_plug_hashes);
  }

  pub fn with_reusable_plug_hashes(mut self, reusable_plug_hashes: Vec<i32>) -> DestinyEntitiesItemsDestinyItemSocketState {
    self.reusable_plug_hashes = Some(reusable_plug_hashes);
    self
  }

  pub fn reusable_plug_hashes(&self) -> Option<&Vec<i32>> {
    self.reusable_plug_hashes.as_ref()
  }

  pub fn reset_reusable_plug_hashes(&mut self) {
    self.reusable_plug_hashes = None;
  }

}



